Update build.yml to build specialised version that we build for fedora 44 too

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -668,6 +668,25 @@ jobs:
           git config --global user.name "GitHub Actions"
           git clone -b ${{ github.event.inputs.tag }} --depth 1 ${{ github.server_url }}/${{ github.repository }}.git
 
+      - name: Patch Turnip Driver (tu_device.cc)
+        shell: bash
+        run: |
+          TARGET_FILE="$HOME/mesa-for-android-container/src/freedreno/vulkan/tu_device.cc"
+          if [ -f "$TARGET_FILE" ]; then
+              echo "Found $TARGET_FILE. Applying patches..."
+              sed -i 's|props->apiVersion = tu_has_multiview(pdevice) ?|props->apiVersion = TU_API_VERSION; //|g' "$TARGET_FILE"
+              sed -i 's|return tu_has_multiview(device);|return true;|' "$TARGET_FILE"
+              sed -i 's|return device->info->props.has_hw_multiview \|\| TU_DEBUG(NOCONFORM);|return true;|' "$TARGET_FILE"
+              sed -i 's|if (pdevice->info->chip >= 7)|if (true)|g' "$TARGET_FILE"
+              sed -i 's|pdevice->info->chip >= 7|pdevice->info->chip >= 6|g' "$TARGET_FILE"
+              sed -i 's|pdevice->info->chip >= 8|pdevice->info->chip >= 6|g' "$TARGET_FILE"
+              sed -i 's|device->info->chip >= 7|device->info->chip >= 6|g' "$TARGET_FILE"
+              echo "Patches applied successfully."
+          else
+              echo "ERROR: File $TARGET_FILE not found!"
+              exit 1
+          fi
+
       - name: Set release name suffix
         shell: bash
         run: |
